spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/tracker_dev?user=tracker&useSSL=false&useTimezone=true&serverTimezone=UTC&useLegacyDatetimeCode=false"

WELCOME_MESSAGE: "Hello from Local"
